[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "describealign"
version = "2.0.6+t.1"
description = "DescribeAlign fork maintained by Trenton Smith"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "GPL-3.0-only" }
authors = [
    { name = "Julian Brown" },
    { name = "Trenton Smith" }
]
dependencies = [
    "numpy",
    "ffmpeg-python",
    "platformdirs",
    "static-ffmpeg",
    "scipy",
    "natsort",
    "sortedcontainers"
]

[project.optional-dependencies]
gui = [
    "wxPython"
]

[project.scripts]
describealign = "describealign:command_line_interface"

[tool.setuptools]
py-modules = ["describealign"]
